### ISSUE TITLE
Homepage dead link

### ISSUE THREAD

**Issue by mehdichaouch** [clappr/website#5]
Hello,

On http://clappr.io website there is a dead link in block:
![image](https://github.com/user-attachments/assets/60ee01cb-cd50-43fc-8863-bfcd7b21c3c1)

it point to this: https://github.com/clappr/clappr/blob/main/doc/EXTERNAL_PLUGINS.md refere to
https://github.com/clappr/website/blob/defb474ac3f4eca0b81094a8804afa807712f580/index.html#L214 which don't exist.

I hope this help.

Best,

**Comment by leaofelipe** [comment]
Thank you for this report, @mehdichaouch 👍🏻 
Issue solved with https://github.com/clappr/website/pull/4#pullrequestreview-2405173871
